spring:

  application:
    name: postsales-backend

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  address: 0.0.0.0
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      status:
        http-mapping:
          DOWN: 200
          OUT_OF_SERVICE: 200
          FATAL: 200
          UNKNOWN: 200
          down: 200
          out-of-service: 200
  health:
    defaults:
      enabled: true
    db:
      enabled: false
    mail:
      enabled: false
    ping:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# Force Railway redeploy 3