spring:

  application:
    name: postsales-backend

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  address: 0.0.0.0
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    defaults:
      enabled: true
    db:
      enabled: true
    mail:
      enabled: false
    ping:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# Force Railway redeploy 3